### ISSUE TITLE
dns.t hangs

### ISSUE THREAD

**Issue by chorny** [powerman/perl-IO-Stream#1]
at least on Windows, when unresolved domain resolves.

If you want to skip tests, you can use following code to check:

```
sub inexistent_domains_do_not_resolve {
  use Socket;
  return 1 unless inet_aton('some.non.existent.host.');
  return 0;
}
```

with recommendation to use Google DNS: 8.8.8.8, 8.8.4.4 or Yandex DNS: 77.88.8.8, 77.88.8.1

**Comment by powerman** [comment]
It's not only on Windows. Thanks.
